// 🌿 src/components/FavoriteDetailsPanel.jsx
import { Trash2, Play } from "lucide-react";

export default function FavoriteDetailsPanel({
  favorite,
    onDelete,
      onStart,
        ecoProgress = 0,
        }) {
          // 💡 Si aucun favori sélectionné
            if (!favorite)
                return (
                      <div className="flex items-center justify-center h-full text-gray-400 italic">
                              Sélectionnez un favori pour voir les détails 🌍
                                    </div>
                                        );

                                          // 🧮 Progression écoPoints simulée
                                            const ecoLive = Math.round((ecoProgress / 100) * favorite.ecoPoints);

                                              return (
                                                  <div className="flex flex-col justify-between h-full p-6 bg-white border-l border-gray-200 shadow-lg rounded-r-2xl transition-all">
                                                        <div>
                                                                <h2 className="text-xl font-semibold text-[#1F2A44] mb-4">
                                                                          Détails du trajet ⭐
                                                                                  </h2>

                                                                                          <p className="text-gray-700">
                                                                                                    <span className="font-medium">Départ :</span> {favorite.from}
                                                                                                            </p>
                                                                                                                    <p className="text-gray-700">
                                                                                                                              <span className="font-medium">Arrivée :</span> {favorite.to}
                                                                                                                                      </p>

                                                                                                                                              <p className="text-gray-700 mt-2">
                                                                                                                                                        <span className="font-medium">Distance :</span>{" "}
                                                                                                                                                                  {favorite.distance?.toFixed(2)} km
                                                                                                                                                                          </p>

                                                                                                                                                                                  <p className="text-gray-700">
                                                                                                                                                                                            <span className="font-medium">ÉcoPoints :</span>{" "}
                                                                                                                                                                                                      {favorite.isSimulating ? (
                                                                                                                                                                                                                  <span className="text-emerald-600 font-semibold">
                                                                                                                                                                                                                                {ecoLive} / {favorite.ecoPoints} 🌿
                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                  favorite.ecoPoints
                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                <div className="mt-6 flex flex-col gap-3">
                                                                                                                                                                                                                                                                                                        {!favorite.isSimulating ? (
                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                              onClick={() => onStart(favorite)}
                                                                                                                                                                                                                                                                                                                                          className="flex items-center justify-center gap-2 bg-emerald-500 hover:bg-emerald-600 text-white px-4 py-2 rounded-full font-medium transition"
                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                <Play className="w-4 h-4" /> Lancer le trajet
                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-center text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                        🚗 Simulation en cours... {ecoProgress.toFixed(0)}%
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => onDelete(favorite._id)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="flex items-center justify-center gap-2 text-red-500 border border-red-500 hover:bg-red-50 px-4 py-2 rounded-full font-medium transition"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Trash2 className="w-4 h-4" /> Supprimer le favori
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
